excluded:
  - Pods
  - R.generated.swift
  - .gundam

opt_in_rules:
  - force_cast
disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - vertical_whitespace
  - unused_optional_binding
  - identifier_name
line_length: 300
file_length: 800
large_tuple: 5
function_body_length: 100
force_cast: warming
